version: "2"
services:
  client:
      image: node:12.16.3
      build: frontend
      ports:
        - "3000:3000"
  api:
      image: node:12.16.3
      build: backend
      ports:
        - "8080:8080"
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: test

